# Simple details input/print template

print("Student Name : Macharla Naga Manoj Reddy")
print("Student_ID = 'CGH2903'")
print("Batch_No = 'PFS-HYD-050'")
print("Email ID= 'manojreddy2710@gmail.com'\n")
print("Date of Birth : 2005-10-27")
print("Age : 20")
print("Gender : Male")
print("Blood Group : O+")
print("City : Nellore")
print("State : Andhra Pradesh")
print("Student Phone Number : +918439797525")
print("Parent Phone Number : +919347767777")
print("Github Link : https://github.com/MacharlaNagamanojreddy\n")
print("College Name : Rmk engineering College")
print("USN Number : 117722201027")
print("Qualification : UG (Bachelor Degrees)")
print("Department : B.Tech - Computer Science (CSE, Cybersecurity, AI & ML, IoT, Cloud Computing, Data Analytics, Data Science)")
print("Pass out Year : 2026")
print("Graduation Percentage : 65%")
print("Arrears : No")
print("No of Arrears : 0")
print("10th Pass Year : 2020")
print("10th Percentage : 99%")
print("12th Pass Year : 2022")
print("12th Percentage : 79%")
print("Skills : Python, Flask, HTML, CSS, Bootstrap, Javascript, MySQL")