print("Name:Manoj Reddy")
print("Age:20")
print("City:Hyderabad")
print("Qualification:B.Tech")
print("Hobbies:Playing Cricket,Watching Movies")
print("Skills:Python,Java,C++")
print("reg no:CGH2903")
print("Batch: 50")
print("College: RMK Engineering College")
print("Department: Artificial Intelligence and Data Science")